### ISSUE TITLE
Crash upon click on "Access logs"

### ISSUE THREAD

**Issue by alazizie** [kamaravichow/safe-dot-android#30]
Crash log generated by Crash Log Viewer https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

`Process: com.aravi.dot
PID: 2898
UID: 10640
Flags: 0x20c8be44
Package: com.aravi.dot v30103 (3.1.3)
Foreground: Yes
Process-Runtime: 136519312
Build: OnePlus/OnePlus7Pro/OnePlus7Pro:11/RKQ1.201022.002/2112101741:user/release-keys

java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at c.c.a.a.a.a$a.b(Unknown Source:2)
	at c.b.a.a.b.d.a.c(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView$r.j(SourceFile:81)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.u1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.f1(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.t0(SourceFile:22)
	at androidx.recyclerview.widget.RecyclerView.s(Unknown Source:38)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23042)
	at android.view.ViewGroup.layout(ViewGroup.java:6419)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23042)
	at android.view.ViewGroup.layout(ViewGroup.java:6419)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23042)
	at android.view.ViewGroup.layout(ViewGroup.java:6419)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23042)
	at android.view.ViewGroup.layout(ViewGroup.java:6419)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23042)
	at android.view.ViewGroup.layout(ViewGroup.java:6419)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23042)
	at android.view.ViewGroup.layout(ViewGroup.java:6419)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:820)
	at android.view.View.layout(View.java:23042)
	at android.view.ViewGroup.layout(ViewGroup.java:6419)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3786)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3227)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2182)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8730)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
	at android.view.Choreographer.doFrame(Choreographer.java:1049)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	... 53 more
`

**Comment by theRoboxx** [comment]
The exact same problem happened to me today.

Description:
The strange part is that the access log doesn't crash and shows the empty screen when the app is fresh installed and "Enable Safe Dot" isn't activated.
I tested it again and it only crashes when i try to open the access log after I enable the accessibility setting.
But if I deactivate the accessibility setting and try it again the app crashes differently and shows a "SafeDot keeps stopping"-window.

Additionally I should say that it worked on LineageOS 19-20220709-NIGHTLY-beryllium from two weeks ago.

I used adb on my laptop and the command 
```
adb logcat | grep -F "`adb shell ps | grep com.aravi.dot  | tr -s [:space:] ' ' | cut -d' ' -f2`"
```
for the logs below. The errors seems to be identical but the codelines are different.

package: com.aravi.dot
version: 3.1.5 from F-Droid
device: xiaomi pocophone f1
os-build: Android 12, LineageOS 19-20220723-NIGHTLY-beryllium
```
FATAL EXCEPTION: main
Process: com.aravi.dot, PID: 10450
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
at c.c.a.a.a.a$a.b(Unknown Source:2)
at c.b.a.a.b.d.a.c(SourceFile:6)
at androidx.recyclerview.widget.RecyclerView$r.j(SourceFile:81)
at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
at androidx.recyclerview.widget.LinearLayoutManager.u1(Unknown Source:0)
at androidx.recyclerview.widget.LinearLayoutManager.f1(SourceFile:2)
at androidx.recyclerview.widget.LinearLayoutManager.t0(SourceFile:22)
at androidx.recyclerview.widget.RecyclerView.s(Unknown Source:38)
at androidx.recyclerview.widget.RecyclerView.q(SourceFile:7)
at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
at android.view.View.layout(View.java:23203)
at android.view.ViewGroup.layout(ViewGroup.java:6412)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
at android.view.View.layout(View.java:23203)
at android.view.ViewGroup.layout(ViewGroup.java:6412)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23203)
at android.view.ViewGroup.layout(ViewGroup.java:6412)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23203)
at android.view.ViewGroup.layout(ViewGroup.java:6412)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23203)
at android.view.ViewGroup.layout(ViewGroup.java:6412)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23203)
at android.view.ViewGroup.layout(ViewGroup.java:6412)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
at android.view.View.layout(View.java:23203)
at android.view.ViewGroup.layout(ViewGroup.java:6412)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3755)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3205)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
at android.view.Choreographer.doCallbacks(Choreographer.java:845)
at android.view.Choreographer.doFrame(Choreographer.java:780)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
... 54 more
```

**Comment by phenelzine** [comment]
reopen the issue please. @kamaravichow  the problem still persist on my device (Samsung galaxy a51)
